### ISSUE TITLE
FilterQueries on a custom-id field doesn't work

### ISSUE THREAD

**Issue by PhilipeLouchtch** [aljazerzen/mongodb-typescript#1]
Hi, I really like this project. In my playing around with it, I have stumbled upon the following issue:

When an entity has a custom-id field, querying that field doesn't work. This is due to the automatic renaming of that field to `_id`. So the logical workaround is to make queries on `_id` instead.

## Example:
Let `User` be defined as such:
```ts
class Person {
    @id name: string;
    something: string;
}
```
When saving a new user (`{name: 'Henk', something: 'Not important'}`)

Then doing the following will not give a result
`userRepository.findOne({name: 'Henk'});`

But this will
`userRepository.findOne({_id: 'Henk'});`

This is confusing and non-obvious. And therefore error-prone. I'm currently working around this with some data duplication:
```ts
class Person {
    @id id: string;
    name: string;
    something: string;
    
    constructor(name: string, something?: string) {
        this.id = name;
        this.name = name;
        this.something = something;
    }
}
```

## Proposed solution:
I think it should be possible for mongodb-typescript to transform queries by renaming id-annotated fields to how it is called in the collection (_id).

**Comment by aljazerzen** [comment]
Yes, this is true, but I am hesitant about implementing this, because it is quite difficult to implement since `name` has to be replaced with `_id` on root level, in `$and` queries, `$or` queries, `$not` queries and maybe somewhere else.

Maybe we can implement this, but I has to be done properly, otherwise it will cause more harm than good.

For now I suggest using `_id` in your queries instead of `name`. Your solution also works, but uses more space in `mongodb` (since you save duplicate data).
