### ISSUE TITLE
Error: cyclic dependency detected when trying to save a NodeJS.Timeout type

### ISSUE THREAD

**Issue by yardenshoham** [aljazerzen/mongodb-typescript#11]
When trying to save an object that has a field of type NodeJS.Timeout a promise rejection occurs.

## Expected Behavior
The document should be inserted without a rejection.

## Current Behavior
An error is thrown.

![image](https://user-images.githubusercontent.com/20454870/71733536-857d5180-2e52-11ea-90f1-c577fa44138c.png)

## Steps to Reproduce
1. Clone this repro repository https://github.com/yardenshoham/reproduce-mongodb-typescript-bug.git
2. Run `npm install`
3. Run `npm start`

Otherwise, here's a script:

```ts

import { ObjectId, MongoClient } from "mongodb";
import { id, Repository } from "mongodb-typescript";

class ReproduceBug {
  @id
  _id: ObjectId;

  aTimeout: NodeJS.Timeout;

  initTimeout() {
    this.aTimeout = setTimeout(() => {
      console.log("1 second");
    }, 1000);
  }
}

async function repro() {
  const client = await MongoClient.connect(
    "mongodb://localhost:27017/repro_bug",
    {
      useNewUrlParser: true
    }
  );

  const buggy = new ReproduceBug();
  buggy.initTimeout();

  console.dir(buggy);


const repository = new Repository<ReproduceBug>(
    ReproduceBug,
    client,
    "items"
  );

  await repository.insert(buggy);
}

repro();
```

**Comment by aljazerzen** [comment]
If I understand correctly, you want to save `NodeJS.Timeout` to mongodb. This is not what this library is for and as far as I know, it cannot be done. `NodeJS.Timeout` is object created internally by NodeJS and thus could not be deserialized.

What you should do is save timeouts to some global (static) variable and only save reference of the timeout to the database:
```ts
class ReproduceBug {
  @id
  _id: ObjectId;

  timeoutReference: number;

  static timeouts: { [reference: number]: NodeJS.Timeout } = {};
  static lastTimeoutReference = 0;

  initTimeout() {
    const timeout = setTimeout(() => {
      console.log("1 second");
    }, 1000);

    ReproduceBug.lastTimeoutReference++;
    this.timeoutReference = ReproduceBug.lastTimeoutReference;
    ReproduceBug.timeouts[this.timeoutReference] = timeout;
  }

  getTimeout() {
    return ReproduceBug.timeouts[this.timeoutReference];
  }
}
```

Note that `getTimeout` would return null after NodeJS process has been restarted (but in such case it doesn't matter since all timeouts also get discarded).
