### ISSUE TITLE
Impossible to make any find request

### ISSUE THREAD

**Issue by liltof** [aljazerzen/mongodb-typescript#19]
Hi ! (the issue might seem long but maybe I just miss something 😅, also, note that this lot of "await" everywhere is due to me desperatly trying everything I could to avoid errors, after the simple exemples did not work)
I've got a model with an ID, declared as follow : 
```
 import {id, ref} from 'mongodb-typescript';
 import { ObjectId } from 'mongodb';

 export class DeliveryModel {

 @id public id: ObjectId
 ...

 }
```
I can save documents without any issue, but when it comes to finding, nothing seems to work, I've tried many ways to do it, but nothing seems to work. Here are the things I tried :
```
console.log("deliveryID", delivery.id)
let deliveryToSave = await this.repository.findById(delivery.id)
let deliveryToSave1 = await this.repository.findOne({_id : delivery.id})
let deliveryToSav2 = await this.repository.find().filter({id : delivery.id})
let deliveryToSav3 = await (await this.repository.find()).filter({_id : delivery.id}).toArray()
let deliveryToSav4 = await (await this.repository.find()).filter({_id : "5fe2127b0ae5aa1d2043ffda"}).toArray()
console.log("findResult", deliveryToSave, deliveryToSave1,  await deliveryToSav2.toArray(), deliveryToSav3, deliveryToSav4)
```
Of course, the id exists in my db and I've checked that many times to be sure
![image](https://user-images.githubusercontent.com/3226611/102907351-3753ca80-4476-11eb-82cd-1370b33ae684.png)

But here is the output : 

```
deliveryID 5fe2127b0ae5aa1d2043ffda
findResult null null [] [] []

```
And when I try to do this : 
`let deliveryToSav5 = await this.repository.find().toArray()`
I get this weird error From class-transformer :
` [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined `

**Comment by scadgek** [comment]
Hey 👋 
Have you tried passing an empty object into `find`?
```
 await this.repository.find({}).toArray()
```

**Comment by liltof** [comment]
> Hey 👋
> Have you tried passing an empty object into `find`?
> 
> ```
>  await this.repository.find({}).toArray()
> ```
Yes, (I was not sure so I tried it again) same error : 
`TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined`

**Comment by liltof** [comment]
Okay, it seems that its apparently partialy due to some fields in the model, but there are many of them. I tried to remove all and just saving an id, but then find with no parameter works, but findOne {id : theId} or { _id : theId } or findById(theId) don't work (no error but returning null)

**Comment by aljazerzen** [comment]
Hey, a bit late to answer this, but here is the deal:

When hydrating the model, this package does some key mapping: it maps your `id` field to be stored as `_id` in mongo (as you saw). This is all good an well, but the problem is that we cannot map keys in queries (it is just to complicated to do it reliably - see #13). So when writing queries, you should substitute `id` with `_id` yourself:

Instead of: 
```
this.repository.findOne({ id : delivery.id })
```

use:
```
this.repository.findOne({ _id : delivery.id })
```
This goes for all `FilterQueries` (used by `findOne`, `findAll`, `filter`...)

As for the second problem about `[ERR_INVALID_ARG_TYPE]`:

This is caused by your model having some field annotated as `@objectId`, but it being undefined and causing problems during deserialization. @liltof Can you isolate the problem and provide me the steps to reproduce it so I can get it fixed?

PS: does anyone know how to enable email notification on new issues on a repo?
