### ISSUE TITLE
question, client side

### ISSUE THREAD

**Issue by jjarrell50** [aljazerzen/mongodb-typescript#3]
I understand use case  mongoDb-db and this is a useful one.  But these types will also be present on the browser side, with the same problem domain; although, it's not a mongo concern. When i pull data across the wire it's going to be a plain object without the setters and functions.  I do have a mechanism to manage this now.

What I do today is define the types on the client side and replicate the same file to the server side. nearly all types are present in both browser and client.

Any suggestions on how to define the types, so that I don't have to resort to two separate definitions for a given type?

**Comment by aljazerzen** [comment]
A bit late but I have a few solutions, none of which are perfect:
1. Files with models and mongodb decorators are included in both projects. This is not optimal, since decorators append some information you don't need at front end to the models. But it would work, just don't use repositories on the front end.
2. Have an shared typescript interface. Back end can define its own models that implement this interface and front end can just use plain models that implement (or *should* implement) the interface, since usually you don't need full hydrated model on the front end.
3. **Use Open API definitions and generate front end definitions from them.** There are plugins that generate a json (or yaml) file which describes how your API can be used. There is a standard for this format and it is called Open API (previously Swagger). Then there are generators that can generate client code for making the calls with all correct types in your own language. I use this method and can say it works well on big projects.
OpenAPI doc generators I used are [@nestjs/swagger](https://github.com/nestjs/swagger) for the Nest framework (Node.js) and [springfox](http://springfox.github.io/springfox/) for Spring framework (Java). Most used client generator is [swagger-codegen](https://github.com/swagger-api/swagger-codegen)
